#!/usr/bin/env bash
# configuring my domain zone

function configure(){
    record=$(dig "$2.$1" | grep -A 1 "ANSWER SECTION" | awk 'NR==2' | awk '{print $4}')
    ip=$(dig "$2.$1" | grep -A 1 "ANSWER SECTION" | awk 'NR==2' | awk '{print $5}')
    echo "The subdomain $2 is a $record and points to $ip"
}

if [ -z "$2" ]
then
    configure "$1" "www"
    configure "$1" "lb-01"
    configure "$1" "web-01"
    configure "$1" "web-02"
else
    configure "$1" "$2"
fi
