#!/usr/bin/env bash
# Installs and configures nginx on the web-01 server

sudo apt-get -y update 
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > var/www/html/index.nginx-debian.html
echo "Hello World!" > var/www/html/index.html
service nginx start
