#!/usr/bin/env bash
# configures a brand new Ubuntu machine so that it's HTTP response contains a custom header.
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $(hostname)" /etc/nginx/sites-enabled/default
