#!/usr/bin/env bash
# configures a new ubuntu machine to act a HAproxy load balancer.

# -- installing the haproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

haproxy_config=\
"
frontend myFrontEnd
        bind *:80
        default_backend myBackEnd

backend myBackEnd
        balance roundrobin
        server 61276-web-01 18.234.253.121:80 check
        server 61276-web-02 52.87.220.207:80 check
"
echo "$haproxy_config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
