#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it.

# dumps all databases
mysqldump -uroot -p"$1" --all-databases > backup.sql

# compress backup.sql to a tar.gz archive
tar -czf "$(date +%d-%m-%Y)".tar.gz backup.sql
