#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes

var=0
while (( var < 13 ))
do
	echo "Hour : $var"
	var2=1
	while (( var2 < 60 ))
	do
		echo "$var2"
		(( var2++ ))
	done
	(( var++ ))
done
