#!/usr/bin/env bash
# Write a Bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the niie after the first dash is displayed (refer to the example)

for line in *
do
	echo "$line" | cut -d- -f2
done
