#!/usr/bin/env bash
# Configures a container to run nginx as "nginx" user

echo "user nginx;" >> /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx/
sed -i '/\[Service\]/a User=nginx/' /lib/systemd/system/nginx.service
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/&\n   listen 0.0.0.0:8080;/' etc/nginx/sites-available/default
sudo kill -9 37
sudo service nginx restart
